---
title: "TCGA BrCa Female Cases Age Dependent Fisher Exact Tests on ER binding"
output:
  pdf_document: default
  word_document: default
date: "`r format(Sys.Date(), '%B %d, %Y')`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE,
	results = "asis"
)
knitr::opts_knit$set(root.dir = here::here())
```

```{r load}
# Load packages
library(tidyverse)
library(glue)
library(cli)
library(pander)
library(ageassn)
panderOptions("knitr.auto.asis", FALSE)

# Constants
fc <- 1.25
fdr <- c(0.05, 0.01)

# Load data
root.dir <- glue("main/code/Analysis_TCGA_BrCa_RNASeq_Expression_Trends/FET_tables/")
tcga_load("Br")
```

```{r data-munging}
# Create data for female breast cancers
tcga_process(cldf, ealldf, annodf, ardf, ezdf, ebdf, ebdf_t1, ebdf_t2, icdf,
             gender = "female")
```

```{r fisher-exact-test-by-ER}
# Combine data for all with ER statuses, read in FET results
EHfs <- c("All", levels(sedf$BrCaEHf))
dct <- tcga_fet(root.dir, fdr, suffix = EHfs)
```

```{r pander-print-by-ER, results='asis'}
# Store case counts and fdr
cat_line("# FET Tables by ER/HER2 status")
ncases <- rep(c("All" = nrow(sedf), table(sedf$BrCaEHf)), length(fdr))
fdrs <- rep(fdr, each = length(EHfs))
walk(seq_along(ncases), ~ {
  cat_line(paste0("## ", names(ncases)[.], " Female Cases, n = ", ncases[.],
                  ", FDR = ", fdrs[.]))
  # Contingency table
  tab <- dct[[.]]
  pander(tab, caption = paste0("FET Table ", names(ncases)[.],
                               " Female Cases, FDR = ", fdrs[.]), digits = 2)
  # FET statistics, with confidence interval of estimate in wrapped in "[ ]"
  stat <- tidy_fet(tab$fisher.ts)
  pander(stat, caption = paste0("FET Statistics ", names(ncases)[.],
                                " Female Cases, FDR = ", fdrs[.]))
  cat_line("\\pagebreak")
})
```

```{r fisher-exact-test-by-iClust}
# Read in FET results for IntClust groups
iCfs <- sort(unique(sedf$IntClust))
dct <- tcga_fet(root.dir, fdr,
                suffix = paste0("iClust", str_pad(iCfs, width = 2, pad = 0)))
```

```{r pander-print-by-iClust, results='asis'}
# Store case counts and fdr
cat_line("# FET Tables by IntClust subgroups")
ncases <- rep(table(sedf$IntClust), length(fdr))
fdrs <- rep(fdr, each = length(iCfs))
walk(seq_along(ncases), ~ {
  cat_line(paste0("## IntClust", names(ncases)[.], " Female Cases, n = ", ncases[.],
                  ", FDR = ", fdrs[.]))
  # Contingency table
  tab <- dct[[.]]
  pander(tab, caption = paste0("FET Table IntClust", names(ncases)[.],
                               " Female Cases, FDR = ", fdrs[.]), digits = 2)
  # FET statistics, with confidence interval of estimate in wrapped in "[ ]"
  stat <- tidy_fet(tab$fisher.ts)
  pander(stat, caption = paste0("FET Statistics IntClust", names(ncases)[.],
                                " Female Cases, FDR = ", fdrs[.]))
  cat_line("\\pagebreak")
})
```
